name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*"
        
    - name: Upload deployment package and script
      run: |
        aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET }}/deploy.zip
        aws s3 cp deploy-using-s3.sh s3://${{ secrets.S3_BUCKET }}/deploy.sh
        
    - name: Execute deployment script
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --parameters commands='[
            "aws s3 cp s3://${{secrets.S3_BUCKET}}/deploy.sh /home/ec2-user/app/deploy.sh",
            "chmod +x /home/ec2-user/app/deploy.sh",
            "/home/ec2-user/app/deploy.sh"
          ]'      
